trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: cognita-azure-sc
  acrName: acratlasdevvsml
  acrLoginServer: acratlasdevvsml.azurecr.io
  imageRepository: ai-service

stages:

- stage: Build
  displayName: Build and Push Image

  jobs:

  - job: DockerBuild

    steps:

    - checkout: self

    - script: |

        docker build \
          docker -version
          docker info
        displayName: verify docker installation
    - task: AzureCLI@2
      displayName: Login to ACR

      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript

        inlineScript: |

          az acr login --name $(acrName)

    - script: |

        docker build \
          -t $(acrLoginServer)/$(imageRepository):$(Build.BuildId) \
          services/ai-service

      displayName: Build Docker Image

    - script: |

        docker push \
          $(acrLoginServer)/$(imageRepository):$(Build.BuildId)

      displayName: Push Docker Image